wandb_version: 1

learning_rate:
  desc: null
  value: 0.005
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 16
loss_function:
  desc: null
  value: tf.keras.losses.MeanSquaredError()
architecture:
  desc: null
  value: Dense
dataset:
  desc: null
  value: Load
_wandb:
  desc: null
  value:
    python_version: 3.10.5
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700225446.589669
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 16
      - 23
      4: 3.10.5
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      10:
      - 9
      13: windows-amd64
